#!/usr/bin/env python3
"""One document for the 0-shot QA sweep across all four models.

Each model's RESULTS.md already carries its QA numbers, but split one table per budget so that the
scores sit next to the generative ones they belong with. That is the right layout for reading a single
budget and the wrong one for the question this sweep was run to answer: how a method degrades as the
budget falls, and whether knowledge survives pruning better than reasoning does. Eighteen tables do
not answer that; four do, plus one that puts the two harnesses side by side.

    python scripts/report_qa_summary.py            # writes docs/qa_summary.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import report_results as rr    # noqa: E402  (same directory, shares the readers and the model table)

# Descending, so a table reads left to right as the budget tightens.
def tiers(rows: dict) -> list[float]:
    return sorted({t for _, t in rows}, reverse=True)


def collect(model: str) -> tuple[dict, dict | None]:
    """{(method, target): (qa_mean, gen_mean, qa_avg, gen_avg)} plus the unpruned row."""
    spec = rr.MODELS[model]
    configs = json.loads(Path(spec["configs"]).read_text())
    configs = [c for c in configs if not c.get("skipped") and not c.get("probe_for")]
    probes = {c["probe_for"]: c for c in json.loads(Path(spec["configs"]).read_text())
              if c.get("probe_for")}
    root = rr.REPO / "results" / model
    rows: dict[tuple[str, float], tuple] = {}
    baseline = None
    for cfg in configs:
        qa = rr.read_qa(root / cfg["dirname"])
        if qa is None or qa["mean"] is None:
            continue
        gen = rr.read_run(root / cfg["dirname"]) or {}
        gen_avg = gen.get("avg")
        if gen_avg is None and cfg["dirname"] in probes:
            probe = rr.read_run(root / probes[cfg["dirname"]]["dirname"])
            gen_avg = (probe or {}).get("avg")
        if gen_avg is None and cfg["method"] in ("Baseline", "Fixed-K"):
            gen_avg = float(cfg["hyper"].split("k=")[1].split()[0].rstrip(")"))
        entry = (qa["mean"], gen.get("mean"), qa["avg"], gen_avg)
        if cfg["method"] == "Baseline":
            baseline = entry
            continue
        for target in cfg["targets"]:
            key = (cfg["method"], float(target))
            # Several configurations of one method can share a tier: a k_min=1 and a k_min=2 variant,
            # and now also the threshold re-solved for the QA prompts alongside the generative one it
            # replaces. The choice is made on the QA average, because that is the budget these scores
            # were spent under: the cheapest row that still spends at least what Fixed-K does, and
            # failing that the closest one. Every row is in the model's own RESULTS.md.
            kept = rows.get(key)
            if kept is not None:
                new_avg, old_avg = qa["avg"], kept[2]
                if new_avg is None or old_avg is None:
                    continue
                new_ok, old_ok = new_avg >= target, old_avg >= target
                better = ((new_ok and not old_ok)
                          or (new_ok == old_ok
                              and (new_avg < old_avg if new_ok else new_avg > old_avg)))
                if not better:
                    continue
            rows[key] = entry
    return rows, baseline


def main() -> int:
    out = [
        "# 0-shot QA across the four models",
        "",
        "Generated by `scripts/report_qa_summary.py`. Four multiple-choice sets — `arc_challenge`, "
        "`arc_easy`, `winogrande`, `openbookqa` — scored by likelihood with nothing generated, `acc` "
        "throughout (winogrande has no `acc_norm`). Every number is the mean of the four; the "
        "per-task columns, the expert counts measured under QA, and the standard errors are in each "
        "model's own `results/<model>/RESULTS.md`.",
        "",
        "Cells are the QA mean, with the gap to the unpruned model in brackets. The thresholds "
        "behind them are not the ones in the generative tables: a threshold admits however many "
        "experts the router's confidence lets it, and the router is more decided about a "
        "one-sentence question than about the middle of a derivation, so the generative settings "
        "spend up to 1.15 fewer experts here than the tier they were calibrated for. Each method "
        "was re-solved against these prompts, and the row shown per tier is the cheapest one that "
        "still spends at least what Fixed-K does.",
        "",
    ]
    per_model = {}
    off_target = [False]
    under = [False]
    for model in ["Qwen3-Next-80B-A3B-Instruct", "Qwen3-30B-A3B-Instruct-2507",
                  "Ling-lite-1.5-2507", "gpt-oss-20b"]:
        rows, base = collect(model)
        if not rows or not base:
            continue
        per_model[model] = (rows, base)
        ts = tiers(rows)
        methods = sorted({m for m, _ in rows},
                         key=lambda m: (rr.row_order({"method": m, "hyper": ""})[0], m))
        native = rr.MODELS[model]["native_k"]
        out += [
            f"## {model}",
            "",
            f"Unpruned (top-{native}): **{base[0]:.2f}**"
            + (f", against {base[1]:.2f} on the generative suite." if base[1] else "."),
            "",
            "| method | " + " | ".join(f"avg {t:.0f}" for t in ts) + " |",
            "| --- | " + " | ".join("---" for _ in ts) + " |",
        ]
        for method in methods:
            cells = []
            for t in ts:
                got = rows.get((method, t))
                if not got:
                    cells.append("—")
                    continue
                # Read against the QA average, since that is what these scores were spent under. Two
                # ways to be off the column: cheaper than Fixed-K, which makes the score unreadable
                # as a comparison, or with no setting that reaches the tier at all, listed at its
                # closest one -- which is how the same number appears in two columns.
                avg = got[2]
                mark = ""
                if avg is not None and avg < t - 0.05:
                    mark, under[0] = " ᵘ", True
                elif avg is not None and avg - t > 0.5:
                    mark, off_target[0] = " ᵛ", True
                cells.append(f"{got[0]:.2f} ({got[0] - base[0]:+.1f}){mark}")
            out.append(f"| {method} | " + " | ".join(cells) + " |")
        out.append("")

    if under[0]:
        out += [
            "ᵘ spends fewer experts than Fixed-K does at that tier, so a lower score here can be "
            "explained by the smaller budget rather than by the method. Its re-solved setting is "
            "queued.",
            "",
        ]
    if off_target[0]:
        out += [
            "ᵛ this method has no setting that reaches that tier, so its closest one is shown, which "
            "spends more experts than the column asks for. It is the same run as the column to its "
            "left where the two agree.",
            "",
        ]

    # The finding this sweep produced, and the reason the QA numbers are worth their own document:
    # the same budget that ruins generation leaves most of the knowledge in place.
    out += [
        "## Knowledge survives what reasoning does not",
        "",
        "Per tier, the worst drop any method takes on QA against the worst it takes on the "
        "generative suite. Same runs, same routers, same budgets — only the question differs.",
        "",
        "| model | tier | worst QA drop | worst generative drop |",
        "| --- | --- | --- | --- |",
    ]
    for model, (rows, base) in per_model.items():
        for t in tiers(rows):
            qa_drops = [got[0] - base[0] for (m, tt), got in rows.items() if tt == t]
            gen_drops = [got[1] - base[1] for (m, tt), got in rows.items()
                         if tt == t and got[1] and base[1]]
            if not qa_drops or not gen_drops:
                continue
            out.append(f"| {model} | avg {t:.0f} | {min(qa_drops):+.1f} | "
                       f"{min(gen_drops):+.1f} |")
    out += [
        "",
        "Read the two columns as answers to different questions rather than as one method doing "
        "better than another. A multiple-choice question is one forward pass over four short "
        "continuations, so a pruned router gets one chance to be wrong; a derivation is thousands of "
        "them, and one bad token early is not recovered. That is also why the expert averages differ "
        "between the two — see the note in each model's report.",
        "",
    ]
    dest = rr.REPO / "docs" / "qa_summary.md"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {dest}  ({len(per_model)} models)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
